baseurl: '/narratives-in-the-wild/'
permalink: pretty
title: 'Narratives in the Wild'

logo:
  mobile: "images/logo/logo.svg"
  mobile_height: "auto"
  mobile_width: "80px"
  desktop: "images/logo/logo.svg"
  desktop_height: "auto"
  desktop_width: "180px"

home: 
  limit_research: 6  # Number of research components to show on homepage

collections:
  research:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research-item"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

# Disable theme to use custom layouts
theme: null

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
